language: ruby
script:
  - bundle exec rake test
  - bundle exec rake rubocop
cache: bundler
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
before_install:
  - gem update --system
  - gem install bundler --no-doc
