language: ruby
script: 
  - bundle exec rake test
  - bundle exec rake rubocop
  - bin/check-fail.sh
cache: bundler
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
before_install: gem install bundler -v 1.11.2
